#ifndef MLD_INCLUDE_COMMON_H
#define MLD_INCLUDE_COMMON_H

// MLD Result Status Codes
#define MLD_SUCCESS			0
#define MLD_FAILURE			1
#define MLD_UNABLE_ALLOCATE_MEMORY	2
#define MLD_INVALID_ARGUMENT		3

// MLD Exit Status Codes
#define MLD_EXIT_SUCCESS	0
#define MLD_EXIT_FAILURE	1

#endif // MLD_INCLUDE_COMMON_H
