#ifndef MLD_INCLUDE_MATRIX_H
#define MLD_INCLUDE_MATRIX_H

#define MLD_MATRIX_ROWS_OFFSET		0
#define MLD_MATRIX_COLUMNS_OFFSET	8
#define MLD_MATRIX_LENGTH_OFFSET	16
#define MLD_MATRIX_ARRAY_OFFSET		24
#define MLD_MATRIX_SIZE			32

#endif // MLD_INCLUDE_MATRIX_H
